---
- name: format iptables
  command: /sbin/iptables -F

- name: save iptables setting
  command: /etc/init.d/iptables save

- name: be sure epel repository is installed
  yum: name=http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm

- name: import epel key
  command: /bin/rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6

- name: disable epel repository
  ini_file: dest=/etc/yum.repos.d/epel.repo section="epel" option="enabled" value="0"

- name: install the tools git/vim
  yum: name={{ item }} state=installed
  with_items:
    - git
    - vim

- name: install memcached
  yum: name={{item}} state=installed enablerepo=epel
  with_items:
    - memcached

- name: run memcached
  service: name=memcached state=started enabled=yes

