---
- name: download nodebrew
  get_url: url="http://git.io/nodebrew" dest=/var/tmp/nodebrew

- name: install nodebrew
  command: perl /var/tmp/nodebrew setup

- name: check .bashrc
  shell: grep '\/\.nodebrew\/current\/bin' $HOME/.bashrc; echo $?
  register: result

- name: rewrite .bashrc for export path
  shell: echo export PATH=$HOME/.nodebrew/current/bin:$PATH > $HOME/.bashrc
  when: result.stdout.find('0') == -1

- name: install nodejs ver{{ node_version }}
  shell: nodebrew install-binary v{{ node_version }}
  ignore_errors: True
  environment:
    PATH: "/home/vagrant/{{ nodebrew_path }}:{{ ansible_env.PATH }}"

- name: use nodejs
  shell: nodebrew use {{ node_version }}
  environment:
    PATH: "/home/vagrant/{{ nodebrew_path }}:{{ ansible_env.PATH }}"

