---
- name: add yum repo for mongodb
  template: src=repo.j2 dest=/etc/yum.repos.d/mongodb.repo
  tags: mongodb

- name: install mongodb server
  yum: name=mongodb-org-server state=present
  tags: mongodb

- name: run mongodb
  service: name=mongod state=started enabled=yes
  tags: mongodb
