---
- name: Infrastructure for Gyazz (memcached,mongo,nodejs)
  hosts: all

  vars:
    node_version: '0.10.26'
    nodebrew_path: '.nodebrew/current/bin'

  roles:
    - { role: base, sudo: yes }
    - { role: nodejs }
    - { role: mongodb, sudo: yes }
